# Generated by Django 5.1.5 on 2025-01-26 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToyotaVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('annual_petroleum_consumption', models.FloatField()),
                ('time_to_charge_at_240v', models.FloatField()),
                ('city_mpg', models.IntegerField()),
                ('city_electricity_consumption', models.FloatField()),
                ('co2_emissions', models.IntegerField()),
                ('combined_mpg', models.IntegerField()),
                ('cylinder_count', models.IntegerField(blank=True, null=True)),
                ('drive_type', models.CharField(max_length=50)),
                ('vehicle_type', models.CharField(max_length=50)),
                ('epa_fuel_score', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=50)),
                ('highway_mpg', models.IntegerField()),
                ('highway_electricity_consumption', models.FloatField()),
                ('trunk_capacity', models.IntegerField()),
                ('transmission_type', models.CharField(max_length=50)),
                ('vehicle_size', models.CharField(max_length=100)),
                ('model_year', models.IntegerField()),
                ('cost_savings', models.IntegerField()),
                ('atv_category', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'toyota_vehicles',
                'managed': False,
            },
        ),
    ]
